Repository robx/pzprjs, pull requests merged in 2023-07, with the labels that each got.

#446 Add Inverse LITSO
  src-ui/changes.html
  src-ui/img/invlitso.png
  src-ui/js/ui/Misc.js
  src-ui/list.html
  src/pzpr/variety.js
  src/res/failcode.en.json
  src/variety/lits.js
  test/script/invlitso.js
  test/variety/lits_test.js
Labels: new genre

#442 Add Heyapin
  src-ui/changes.html
  src-ui/img/heyapin.png
  src-ui/js/ui/KeyPopup.js
  src-ui/js/ui/Misc.js
  src-ui/list.html
  src-ui/p.html
  src-ui/res/p.en.json
  src-ui/res/p.ja.json
  src/puzzle/MouseInput.js
  src/pzpr/variety.js
  src/res/failcode.en.json
  src/variety/heyapin.js
  src/variety/ladders.js
  test/script/heyapin.js
  test/script/ladders.js
Labels: new genre

#456 Add function presets for MouseInput
  src/puzzle/MouseInput.js
  src/variety-common/MouseInput.js
  src/variety/anglers.js
  src/variety/aqre.js
  src/variety/araf.js
  src/variety/cbanana.js
  src/variety/cbblock.js
  src/variety/chainedb.js
  src/variety/context.js
  src/variety/dominion.js
  src/variety/factors.js
  src/variety/fillmat.js
  src/variety/geradeweg.js
  src/variety/hashikake.js
  src/variety/heyawake.js
  src/variety/hitori.js
  src/variety/ichimaga.js
  src/variety/kurodoko.js
  src/variety/kusabi.js
  src/variety/lookair.js
  src/variety/mashu.js
  src/variety/nawabari.js
  src/variety/numlin.js
  src/variety/nurikabe.js
  src/variety/ququ.js
  src/variety/renban.js
  src/variety/ripple.js
  src/variety/scrin.js
  src/variety/shikaku.js
  src/variety/shimaguni.js
  src/variety/squarejam.js
  src/variety/sudoku.js
  src/variety/sukoro.js
  src/variety/tapa.js
  src/variety/tawa.js
  src/variety/wblink.js
Labels: enhancement

#458 bdwalk: Implement maximum height
  src-ui/changes.html
  src-ui/js/ui/MenuConfig.js
  src-ui/p.html
  src-ui/res/p.en.json
  src-ui/res/p.ja.json
  src-ui/res/rules.en.yaml
  src/puzzle/Config.js
  src/res/failcode.en.json
  src/res/failcode.ja.json
  src/variety/haisu.js
  test/puzzle/answer_test.js
  test/script/bdwalk.js
Labels: bug, enhancement

#460 Add "Outline shaded cells" button to slitherlink
  src-ui/js/ui/ToolArea.js
  src-ui/p.html
  src-ui/res/p.en.json
  src/variety/slither.js
  test/variety/slither_test.js
Labels: enhancement

#453 Add Tetrochain
  src-ui/changes.html
  src-ui/img/tetrochain.png
  src-ui/js/ui/KeyPopup.js
  src-ui/js/ui/Misc.js
  src-ui/list.html
  src/pzpr/variety.js
  src/res/failcode.en.json
  src/variety/kuroclone.js
  src/variety/tetrochain.js
  test/script/tetrochain.js
Labels: new genre

#465 compass: Fix editing in bottomright cell
  src/puzzle/KeyInput.js
  test/script/compass.js
Labels: bug

#454 Add Brownies
  src-ui/changes.html
  src-ui/img/brownies.png
  src-ui/js/ui/KeyPopup.js
  src-ui/js/ui/Misc.js
  src-ui/list.html
  src/pzpr/variety.js
  src/res/failcode.en.json
  src/variety/yosenabe.js
  test/script/brownies.js
Labels: new genre

#450 Add Sashikazune
  src-ui/changes.html
  src-ui/img/sashikazune.png
  src-ui/js/ui/KeyPopup.js
  src-ui/js/ui/Misc.js
  src-ui/list.html
  src/pzpr/variety.js
  src/res/failcode.en.json
  src/variety/loute.js
  test/script/sashikazune.js
Labels: new genre
