Repository robx/pzprjs, pull requests merged in 2024-09, with the labels that each got.

#562 Add pause button
  src-ui/css/ui.css
  src-ui/js/ui/Timer.js
  src-ui/js/ui/ToolArea.js
  src-ui/p.html
  src-ui/res/p.en.json
  src-ui/res/p.ja.json
  src/puzzle/KeyInput.js
  src/puzzle/Puzzle.js
Labels: enhancement

#565 parser: Allow importing URLs in Duplicate URL format
  src/puzzle/FileData.js
  src/pzpr/parser.js
  test/.eslintrc.json
  test/pzpr/parser_test.js
Labels: enhancement

#544 Add Turnaround
  package-lock.json
  src-ui/changes.html
  src-ui/img/turnaround.png
  src-ui/js/ui/KeyPopup.js
  src-ui/js/ui/Misc.js
  src-ui/list.html
  src-ui/res/history.en.yaml
  src-ui/res/history.ja.yaml
  src-ui/res/rules.en.yaml
  src/puzzle/Config.js
  src/pzpr/variety.js
  src/res/failcode.en.json
  src/variety/turnaround.js
  test/script/turnaround.js
Labels: new genre

#567 Add Twin Area
  src-ui/changes.html
  src-ui/list.html
  src/puzzle/Config.js
  src/pzpr/variety.js
  src/res/failcode.en.json
  src/variety/hanare.js
  test/script/twinarea.js
Labels: new genre

#572 Upgrade test Action to use Node 20
  .github/workflows/test.yml
Labels: dependencies

#570 Add Smullyanic Dynasty
  src-ui/changes.html
  src-ui/img/smullyan.png
  src-ui/js/ui/KeyPopup.js
  src-ui/js/ui/Misc.js
  src-ui/list.html
  src/pzpr/variety.js
  src/res/failcode.en.json
  src/variety/context.js
  test/script/smullyan.js
Labels: new genre
