Repository robx/pzprjs, pull requests merged in 2025-08, with the labels that each got.

#638 Add Number City
  src-ui/changes.html
  src-ui/img/numcity.png
  src-ui/js/ui/KeyPopup.js
  src-ui/js/ui/Misc.js
  src-ui/list.html
  src/pzpr/variety.js
  src/res/failcode.en.json
  src/variety/fillomino.js
  test/script/numcity.js
Labels: new genre

#642 Fixed issue with circles answer checking for Nanro
  src/variety/nanro.js
  test/script/nanro.js
Labels: bug

#644 Adding "grey correct numbers" to Tasquare
  src/variety/tasquare.js
Labels: enhancement
